# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: linux-1

on:
  push:
    branches: [ build, test ]

jobs:
  build:

    runs-on: ubuntu-20.04
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip build]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip linux]')"
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use oxr463/setup-cordova
      uses: oxr463/setup-cordova@0.0.3

    # before_install:
    - run: apt-get install imagemagick -y
    - run: npm run pre
    - run: npm i
    - run: npm run prepare
    - run: npm run icon
    - run: npm run splash
    - run: npm run build-android
    - run: npm run cp

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.apk"
        tags: true
        draft: true

